const fs = require('fs');

const expressions = [
  ["s'il vous plaît", "por favor (formal/plural)", "A1", "Un café, s'il vous plaît.", "Um café, por favor."],
  ["s'il te plaît", "por favor (informal)", "A1", "Aide-moi, s'il te plaît.", "Ajude-me, por favor."],
  ["bien sûr", "claro / certamente", "A1", "Oui, bien sûr !", "Sim, claro!"],
  ["tout à fait", "exatamente / perfeitamente", "A2", "C'est tout à fait ça.", "É exatamente isso."],
  ["c'est-à-dire", "ou seja / quer dizer", "B1", "C'est-à-dire que nous sommes en retard.", "Ou seja, estamos atrasados."],
  ["parce que", "porque", "A1", "Je mange parce que j'ai faim.", "Eu como porque tenho fome."],
  ["en fait", "na verdade / de fato", "A2", "En fait, c'est très simple.", "Na verdade, é muito simples."],
  ["quand même", "mesmo assim / de qualquer forma", "A2", "Merci quand même.", "Obrigado mesmo assim."],
  ["au revoir", "até logo / tchau", "A1", "Au revoir, bonne journée !", "Tchau, bom dia!"],
  ["bonjour", "bom dia / olá", "A1", "Bonjour, comment allez-vous ?", "Bom dia, como vai?"],
  ["bonne nuit", "boa noite", "A1", "Bonne nuit, fais de beaux rêves.", "Boa noite, bons sonhos."],
  ["bonsoir", "boa noite (chegada)", "A1", "Bonsoir tout le monde.", "Boa noite a todos."],
  ["à bientôt", "até breve", "A1", "Merci pour tout, à bientôt !", "Obrigado por tudo, até breve!"],
  ["à plus tard", "até mais tarde", "A1", "Je dois partir, à plus tard.", "Tenho que ir, até mais tarde."],
  ["à tout à l'heure", "até logo mais", "A2", "On se voit à tout à l'heure.", "Nos vemos logo mais."],
  ["d'accord", "de acordo / ok", "A1", "D'accord, je comprends.", "Ok, eu entendo."],
  ["ça va", "tudo bem / vai bem", "A1", "Salut, ça va ?", "Oi, tudo bem?"],
  ["comme ci, comme ça", "mais ou menos", "A1", "Aujourd'hui, c'est comme ci, comme ça.", "Hoje, é mais ou menos."],
  ["de rien", "de nada", "A1", "Merci ! - De rien.", "Obrigado! - De nada."],
  ["je vous en prie", "de nada / não há de quê (formal)", "A2", "Merci beaucoup. - Je vous en prie.", "Muito obrigado. - De nada."],
  ["je t'en prie", "de nada (informal)", "A2", "Merci. - Je t'en prie.", "Obrigado. - De nada."],
  ["avec plaisir", "com prazer", "A1", "Puis-je vous aider ? Avec plaisir.", "Posso ajudá-lo? Com prazer."],
  ["pas du tout", "de jeito nenhum / absolutamente não", "A2", "Tu es fatigué ? Pas du tout.", "Você está cansado? Absolutamente não."],
  ["pas de problème", "sem problema", "A1", "Pas de problème, je m'en occupe.", "Sem problema, eu cuido disso."],
  ["bien sûr que non", "claro que não", "A2", "Tu veux abandonner ? Bien sûr que non.", "Você quer desistir? Claro que não."],
  ["peut-être", "talvez", "A1", "Peut-être qu'il viendra demain.", "Talvez ele venha amanhã."],
  ["en effet", "com efeito / de fato", "B1", "En effet, c'est une excellente idée.", "De fato, é uma excelente ideia."],
  ["par contre", "em compensação / por outro lado", "B1", "C'est cher, par contre c'est très beau.", "É caro, em compensação é muito bonito."],
  ["en revanche", "em contrapartida / por outro lado", "B2", "Le projet est long, en revanche il est passionnant.", "O projeto é longo, em contrapartida é fascinante."],
  ["à propos", "a propósito", "A2", "À propos, avez-vous vu mon livre ?", "A propósito, vocês viram meu livro?"],
  ["d'ailleurs", "aliás / além disso", "B1", "Je ne sais pas, d'ailleurs je m'en fiche.", "Eu não sei, aliás eu não me importo."],
  ["au fait", "a propósito / por falar nisso", "B1", "Au fait, tu as appelé ton frère ?", "A propósito, você ligou para o seu irmão?"],
  ["par exemple", "por exemplo", "A1", "J'aime les fruits, par exemple les pommes.", "Eu gosto de frutas, por exemplo, maçãs."],
  ["c'est ça", "é isso aí / exato", "A1", "Tu as compris, c'est ça !", "Você entendeu, é isso aí!"],
  ["n'est-ce pas", "não é mesmo?", "A2", "Il fait beau aujourd'hui, n'est-ce pas ?", "O tempo está bom hoje, não é mesmo?"],
  ["un petit peu", "um pouquinho", "A1", "Je parle un petit peu français.", "Eu falo um pouquinho de francês."],
  ["beaucoup de", "muito / muita", "A1", "Il y a beaucoup de monde ici.", "Há muita gente aqui."],
  ["trop de", "demais / em excesso", "A1", "Il y a trop de bruit.", "Há muito barulho."],
  ["assez de", "o suficiente de / bastante", "A2", "Nous avons assez de temps.", "Temos tempo suficiente."],
  ["peu de", "pouco", "A2", "Il y a très peu de chances.", "Há muito poucas chances."],
  ["pas mal de", "bastante / muitos", "B1", "J'ai pas mal de travail.", "Eu tenho bastante trabalho."],
  ["tout le monde", "todo mundo", "A1", "Bonjour tout le monde !", "Bom dia, todo mundo!"],
  ["tous les jours", "todos os dias", "A1", "Je travaille tous les jours.", "Eu trabalho todos os dias."],
  ["de temps en temps", "de vez em quando", "A2", "Je lis de temps en temps.", "Eu leio de vez em quando."],
  ["en ce moment", "neste momento", "A2", "Il pleut en ce moment.", "Está chovendo neste momento."],
  ["tout de suite", "imediatamente", "A2", "Je viens tout de suite.", "Eu vou imediatamente."],
  ["plus tard", "mais tarde", "A1", "Nous verrons ça plus tard.", "Veremos isso mais tarde."],
  ["à côté de", "ao lado de", "A1", "La banque est à côté de la poste.", "O banco fica ao lado dos correios."],
  ["en face de", "em frente de", "A1", "Il habite en face de l'école.", "Ele mora em frente à escola."],
  ["près de", "perto de", "A1", "C'est très près de chez moi.", "Fica muito perto da minha casa."],
  ["loin de", "longe de", "A1", "Nous habitons loin de la ville.", "Moramos longe da cidade."],
  ["au-dessus de", "acima de", "B1", "L'avion vole au-dessus de la mer.", "O avião voa acima do mar."],
  ["en dessous de", "abaixo de", "B1", "La température est en dessous de zéro.", "A temperatura está abaixo de zero."],
  ["au milieu de", "no meio de", "A2", "La table est au milieu de la pièce.", "A mesa está no meio do cômodo."],
  ["au lieu de", "em vez de", "B1", "Je prendrai du thé au lieu de café.", "Eu vou tomar chá em vez de café."],
  ["grâce à", "graças a", "B1", "J'ai réussi grâce à toi.", "Eu consegui graças a você."],
  ["à cause de", "por causa de", "A2", "Il est en retard à cause du trafic.", "Ele está atrasado por causa do trânsito."],
  ["pour que", "para que", "B1", "Je parle fort pour que tu m'entendes.", "Falo alto para que você me ouça."],
  ["bien que", "embora", "B2", "Bien qu'il soit tard, je vais sortir.", "Embora seja tarde, eu vou sair."],
  ["avant de", "antes de", "A2", "Lave-toi les mains avant de manger.", "Lave as mãos antes de comer."],
  ["après avoir", "depois de ter", "B1", "Après avoir mangé, il est parti.", "Depois de ter comido, ele foi embora."],
  ["après être", "depois de ser/estar/ir", "B1", "Après être arrivé, il a dormi.", "Depois de ter chegado, ele dormiu."],
  ["en train de", "fazendo (algo) / em processo de", "A2", "Je suis en train de lire.", "Estou lendo (neste momento)."],
  ["avoir besoin de", "precisar de", "A2", "J'ai besoin de ton aide.", "Preciso da sua ajuda."],
  ["avoir envie de", "ter vontade de", "A2", "J'ai envie de voyager.", "Tenho vontade de viajar."],
  ["avoir hâte de", "estar ansioso para", "B1", "J'ai hâte de te voir.", "Estou ansioso para te ver."],
  ["avoir peur de", "ter medo de", "A2", "Il a peur de l'obscurité.", "Ele tem medo do escuro."],
  ["avoir l'air", "parecer", "A2", "Elle a l'air fatiguée.", "Ela parece cansada."],
  ["faire attention", "prestar atenção / tomar cuidado", "A2", "Fais attention en traversant la rue.", "Preste atenção ao atravessar a rua."],
  ["se rendre compte", "dar-se conta / perceber", "B1", "Il s'est rendu compte de son erreur.", "Ele se deu conta do seu erro."],
  ["il y a", "há / tem", "A1", "Il y a un chat dans le jardin.", "Há um gato no jardim."],
  ["il s'agit de", "trata-se de", "B1", "Il s'agit d'un problème très grave.", "Trata-se de um problema muito grave."],
  ["n'importe quoi", "qualquer coisa / bobagem", "B1", "Il dit n'importe quoi.", "Ele diz bobagem."],
  ["n'importe qui", "qualquer um", "B1", "N'importe qui peut le faire.", "Qualquer um pode fazer isso."],
  ["n'importe quand", "a qualquer momento", "B1", "Tu peux venir n'importe quand.", "Você pode vir a qualquer momento."],
  ["n'importe où", "em qualquer lugar", "B1", "Je te suivrai n'importe où.", "Eu te seguirei em qualquer lugar."],
  ["quelque chose", "alguma coisa", "A1", "As-tu mangé quelque chose ?", "Você comeu alguma coisa?"],
  ["quelqu'un", "alguém", "A1", "Il y a quelqu'un à la porte.", "Tem alguém na porta."],
  ["pourquoi pas", "por que não?", "A1", "Aller au cinéma ? Pourquoi pas !", "Ir ao cinema? Por que não!"],
  ["c'est-à-dire que", "ou seja que", "B2", "C'est-à-dire que je ne suis pas sûr.", "Ou seja que eu não tenho certeza."],
  ["quant à", "quanto a", "B1", "Quant à moi, je préfère rester.", "Quanto a mim, prefiro ficar."],
  ["me va", "cai bem em mim / me serve", "A2", "Cette chemise me va très bien.", "Esta camisa me serve muito bem."],
  ["te va", "cai bem em você / te serve", "A2", "Ce manteau te va parfaitement.", "Este casaco te cai perfeitamente."],
  ["lui va", "cai bem nele/nela / lhe serve", "A2", "La robe lui va à merveille.", "O vestido lhe cai às maravilhas."],
  ["vous va", "cai bem em você/vocês / vos serve", "A2", "Cette couleur vous va bien.", "Esta cor lhe cai bem."],
  ["nous va", "cai bem em nós / nos serve", "A2", "Ce rendez-vous nous va.", "Este compromisso nos serve (está bom para nós)."],
  ["leur va", "cai bem neles/nelas / lhes serve", "A2", "Cette maison leur va très bien.", "Esta casa lhes serve muito bem."],
  ["mon Dieu", "meu Deus", "A1", "Oh mon Dieu, c'est incroyable !", "Oh meu Deus, é incrível!"],
  ["c'est grave", "é grave", "A2", "Le médecin a dit que c'est grave.", "O médico disse que é grave."],
  ["ce n'est pas grave", "não é grave / não tem problema", "A2", "Ce n'est pas grave, on peut réparer ça.", "Não tem problema, podemos consertar isso."],
  ["prendre du recul", "dar um passo para trás / ver de outra perspectiva", "B2", "Il faut prendre du recul pour analyser la situation.", "É preciso dar um passo para trás para analisar a situação."],
  ["coup de foudre", "amor à primeira vista", "B1", "Entre eux, c'était le coup de foudre.", "Entre eles, foi amor à primeira vista."],
  ["du coup", "então / por isso / consequentemente", "B1", "Il pleuvait, du coup on est restés à la maison.", "Estava chovendo, então ficamos em casa."],
  ["bien sûr que si", "claro que sim", "A2", "Tu ne viens pas ? Bien sûr que si !", "Você não vem? Claro que sim!"],
  ["plus ou moins", "mais ou menos", "A2", "Le travail est plus ou moins terminé.", "O trabalho está mais ou menos terminado."]
];

let content = `import { DictionaryEntry } from '../utils/textParser';\n\nexport const COMMON_EXPRESSIONS: Record<string, Omit<DictionaryEntry, 'term'>> = {\n`;

expressions.forEach(exp => {
  const [fr, pt, level, exFr, exPt] = exp;
  const escapedFr = fr.replace(/"/g, '\\"');
  
  content += `  "${escapedFr}": {
    wordFr: "${escapedFr}",
    definitionPt: "${pt}",
    definitionFr: "Expression idiomatique ou tournure très fréquente",
    difficultyLevel: "${level}",
    isDictionaryTerm: false,
    examples: [
      { level: "${level}", fr: "${exFr.replace(/"/g, '\\"')}", pt: "${exPt.replace(/"/g, '\\"')}" }
    ]
  },\n`;
});

content += '};\n';
fs.writeFileSync('src/data/commonExpressionsDictionary.ts', content);
